name: 03 - Node CI (Install & Test, only if present)

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies (npm ci)
        if: hashFiles('package.json') != ''
        run: |
          if [ -f package-lock.json ]; then
            npm ci
          else
            npm install
          fi

      - name: Run tests (if present)
        run: npm run -s test --if-present || echo "No tests to run"

      - name: Done
        run: echo "🎉 CI completed on $GITHUB_SHA"
